FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_PANORAMA_SERVER
ARG VITE_OIDC_ENABLED=false
ARG VITE_AZURE_CLIENT_ID
ARG VITE_AZURE_AUTHORITY
ARG VITE_AZURE_REDIRECT_URI

ENV VITE_PANORAMA_SERVER=$VITE_PANORAMA_SERVER
ENV VITE_OIDC_ENABLED=$VITE_OIDC_ENABLED
ENV VITE_AZURE_CLIENT_ID=$VITE_AZURE_CLIENT_ID
ENV VITE_AZURE_AUTHORITY=$VITE_AZURE_AUTHORITY
ENV VITE_AZURE_REDIRECT_URI=$VITE_AZURE_REDIRECT_URI

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
