#!/bin/bash
# =============================================================================
# Panovision Installation Script for RHEL 9
# Generated by Panovision Installer Gen at 2025-12-09T03:29:17.976Z
# Repository: https://github.com/gsk-panda/New-Panovision
# =============================================================================

# Exit on any error
set -e

# Configuration Variables
REPO_URL="https://github.com/gsk-panda/New-Panovision"
INSTALL_DIR="/opt/panovision"
SERVICE_USER="panouser"
SERVICE_NAME="panovision"
APP_PORT="8000"
PYTHON_CMD="python3"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log() {
    echo -e "${BLUE}[INFO] $1${NC}"
}

error() {
    echo -e "${RED}[ERROR] $1${NC}"
    exit 1
}

log "Starting installation process for RHEL 9..."

# 1. Update System
log "Updating system packages..."
sudo dnf update -y

# 2. Install Dependencies
log "Installing dependencies (git, $PYTHON_CMD, pip, tar)..."
sudo dnf install -y git $PYTHON_CMD python3-pip tar epel-release

# Ensure pip is upgraded
$PYTHON_CMD -m pip install --upgrade pip

# 3. Create Service User
if id "$SERVICE_USER" &>/dev/null; then
    log "User $SERVICE_USER already exists."
else
    log "Creating user $SERVICE_USER..."
    sudo useradd -m -s /bin/bash "$SERVICE_USER"
fi

# 4. Clone Repository
if [ -d "$INSTALL_DIR" ]; then
    log "Directory $INSTALL_DIR already exists. Pulling latest changes..."
    cd "$INSTALL_DIR"
    sudo -u "$SERVICE_USER" git pull
else
    log "Cloning repository to $INSTALL_DIR..."
    sudo mkdir -p "$INSTALL_DIR"
    sudo chown "$SERVICE_USER":"$SERVICE_USER" "$INSTALL_DIR"
    sudo -u "$SERVICE_USER" git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# 5. Setup Python Virtual Environment
log "Setting up Python virtual environment..."
sudo -u "$SERVICE_USER" $PYTHON_CMD -m venv venv
sudo -u "$SERVICE_USER" ./venv/bin/pip install -r requirements.txt || log "No requirements.txt found, skipping pip install."

# 6. Create Systemd Service
log "Creating Systemd service file for $SERVICE_NAME..."
cat <<EOF | sudo tee /etc/systemd/system/$SERVICE_NAME.service
[Unit]
Description=Panovision Application Service
After=network.target

[Service]
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
ExecStart=$INSTALL_DIR/venv/bin/python main.py
Restart=always
Environment=PORT=$APP_PORT

[Install]
WantedBy=multi-user.target
EOF

log "Reloading systemd daemon..."
sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"

# 7. Configure Firewall
log "Configuring firewall to allow traffic on port $APP_PORT..."
sudo firewall-cmd --permanent --add-port=$APP_PORT/tcp
sudo firewall-cmd --reload


# 8. Configure Nginx (Optional)
log "Installing and configuring Nginx..."
sudo dnf install -y nginx
sudo systemctl enable nginx
sudo systemctl start nginx

cat <<EOF | sudo tee /etc/nginx/conf.d/$SERVICE_NAME.conf
server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:$APP_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
EOF

sudo nginx -t && sudo systemctl reload nginx
sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --reload
log "Nginx configured successfully."


log "Installation Completed Successfully!"
log "Service Status:"
sudo systemctl status "$SERVICE_NAME" --no-pager
